# Server Port : 
server.port=8081

# Database Configuration :
spring.datasource.url=jdbc:mysql://localhost:3306/employee_db
spring.datasource.username=root
spring.datasource.password=Zezohelal11
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# eureka server configuration : 
eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.registry-fetch-interval-seconds=5

# Basic log levels
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.net.abdelaziz=DEBUG

# Feign logging
logging.level.feign=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG

# Trace ID
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# Console log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [${spring.application.name}] [traceId=%X{traceId}] [%thread] %-5level %logger{36} - %msg%n

# File logging (separate per service)
logging.file.name=logs/${spring.application.name}.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [${spring.application.name}] [traceId=%X{traceId}] [%thread] %-5level %logger{36} - %msg%n
